name: Update SafeZoneGOV Data

on:
  schedule:
    - cron: "0 0 * * 1"  # Runs every Monday at midnight UTC
  workflow_dispatch:  # Allows manual execution

jobs:
  update-crime-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install pandas gspread google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client pyarrow

      - name: Add Google Credentials
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: echo "$GOOGLE_CREDENTIALS" > google-credentials.json

      - name: Run Data Processing Script
        run: python preprocess_gov_data.py  # Make sure this matches your script filename
